spring.application.name=resumeanalyzer
# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/resume_analyzer_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=161044

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Gemini AI Key
gemini.api.key=${GEMINI_API_KEY}
